spring.application.name=api-gateway

server.port=9191
#
#
#
##Eureka server clinet kathawa
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

## Send traces to Zipkin
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
#
## Sample 100% of requests (1.0 = 100%)
#management.tracing.sampling.probability=1.0
#
#
##Config server eken load krgann kiyala kiynnona
#spring.config.import=optional:configserver:http://localhost:8888
##Actuator refrehs endpoints
#management.endpoints.web.exposure.include=*

# JWT Configuration
jwt.secret=U4gGelTWCHRgC0NqpI2faxhMtvX7L9zfy7oBUWosUgBy7obkjdCD1pmk/yRXAN85nuZOaw0N80YFQy2stYVCvw==
#jwt.expiration=3600*5

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true


spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:8081
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

